// Generated by Supabase CLI - will be updated after running migrations

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          created_at?: string
          updated_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          user_id: string
          title: string
          description: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          description?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          description?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      scripts: {
        Row: {
          id: string
          project_id: string
          content: Json
          platform: string
          duration: number
          tone: string
          cost: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          project_id: string
          content: Json
          platform: string
          duration: number
          tone: string
          cost: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          content?: Json
          platform?: string
          duration?: number
          tone?: string
          cost?: number
          created_at?: string
          updated_at?: string
        }
      }
      videos: {
        Row: {
          id: string
          project_id: string
          original_url: string
          processed_url: string | null
          status: 'uploaded' | 'processing' | 'completed' | 'failed'
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          project_id: string
          original_url: string
          processed_url?: string | null
          status?: 'uploaded' | 'processing' | 'completed' | 'failed'
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          original_url?: string
          processed_url?: string | null
          status?: 'uploaded' | 'processing' | 'completed' | 'failed'
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      jobs: {
        Row: {
          id: string
          video_id: string
          status: 'queued' | 'processing' | 'completed' | 'failed'
          progress: number
          error: string | null
          output_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          video_id: string
          status?: 'queued' | 'processing' | 'completed' | 'failed'
          progress?: number
          error?: string | null
          output_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          video_id?: string
          status?: 'queued' | 'processing' | 'completed' | 'failed'
          progress?: number
          error?: string | null
          output_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
  }
}

